apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wappip 
  name: wappip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wappip
  template:
    metadata:
      labels:
        app: wappip
    spec:
      containers:
      - name: wappip
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80