apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myscecret 
  name: myscecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myscecret
  template:
    metadata:
      labels:
        app: myscecret
    spec:
      containers:
      - name: myscecret
        image: alpine:latest
        command: ["sleep", "9999"]
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: password